# Change these first
owner: jermynstreettheatre # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Public website
    url: https://www.jermynstreettheatre.co.uk
  - name: GAVIN
    url: https://assets.technical.jermynstreettheatre.co.uk
    assignees:
      - edwardcallow
  - name: Vaultwarden
    url: https://vault.technical.jermynstreettheatre.co.uk
    assignees:
      - edwardcallow
  - name: Email IMAP
    check: tcp-ping
    url: mail.jermynstreettheatre.co.uk
    port: 993
  - name: Email POP3
    check: tcp-ping
    url: mail.jermynstreettheatre.co.uk
    port: 995
  - name: Email SMTP
    check: tcp-ping
    url: mail.jermynstreettheatre.co.uk
    port: 465

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/jermynstreettheatre/status/master/assets/jst-purple-logo.png
  favicon: https://raw.githubusercontent.com/jermynstreettheatre/status/master/assets/jst-white-purple-logo.png
  name: JST Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
